saucedemoUrl = https://www.saucedemo.com/
reqresUrl = https://reqres.in/
catfactsUrl = https://catfact.ninja/

#Timeout
wait.timeout.seconds=30

#Browser
browser=chrome

kafka.local.bootstrap.servers=localhost:9092